name = "krishnagsvv"
compatibility_date = "2025-08-27"

[assets]
directory = "./dist"

[build]
command = "npm run build"

# Production environment
[env.production]
name = "krishnagsvv"

# Preview environment for feature branches
[env.preview]
name = "krishnagsvv-preview"
